all:
	clang++ -std=c++11 -shared -o sfmlNibblerLib.dylib -I ~/.brew/Cellar/sfml/2.5.1/include -L ~/.brew/Cellar/sfml/2.5.1/lib -lsfml-graphics -lsfml-system -lsfml-window sfml.cpp
	export LD_LIBRARY_PATH=~/.brew/sfml/Cellar/sfml/2.5.1/lib
